A	.cursor/debug.log
A	.dockerignore
A	.gitignore
A	.idea/compiler.xml
M	.idea/dataSources.local.xml
A	.idea/encodings.xml
A	.idea/jarRepositories.xml
M	.idea/misc.xml
D	.idea/modules.xml
A	Dockerfile
A	add_admin.sql
M	add_long_term_room.sql
M	admin_dashboard_migration.sql
A	backup.sql
A	docker-compose.yml
A	docker/init.sql
M	insertion.sql
A	src/main/java/com/rentaroom/config/FilterConfig.java
M	src/main/java/com/rentaroom/controller/AdminController.java
M	src/main/java/com/rentaroom/controller/DashboardController.java
A	src/main/java/com/rentaroom/controller/GlobalExceptionLogger.java
M	src/main/java/com/rentaroom/controller/HomeController.java
A	src/main/java/com/rentaroom/filter/ExceptionLoggingFilter.java
M	src/main/java/com/rentaroom/repository/BookingRepository.java
A	src/main/java/com/rentaroom/repository/BookingRepositoryCustom.java
A	src/main/java/com/rentaroom/repository/BookingRepositoryImpl.java
M	src/main/java/com/rentaroom/repository/PaymentRepository.java
A	src/main/java/com/rentaroom/repository/PaymentRepositoryCustom.java
A	src/main/java/com/rentaroom/repository/PaymentRepositoryImpl.java
M	src/main/java/com/rentaroom/repository/RoomRepository.java
A	src/main/java/com/rentaroom/repository/RoomRepositoryCustom.java
A	src/main/java/com/rentaroom/repository/RoomRepositoryImpl.java
M	src/main/java/com/rentaroom/repository/UserRepository.java
A	src/main/java/com/rentaroom/repository/specification/BookingSpecifications.java
A	src/main/java/com/rentaroom/repository/specification/RoomSpecifications.java
A	src/main/java/com/rentaroom/repository/specification/UserSpecifications.java
M	src/main/java/com/rentaroom/service/AdminService.java
M	src/main/java/com/rentaroom/service/RoomService.java
M	src/main/resources/application.properties
M	src/main/resources/templates/admin/dashboard.html
M	src/main/resources/templates/admin/users.html
M	src/main/resources/templates/dashboard.html
M	src/main/resources/templates/layout.html
M	src/main/resources/templates/room-detail.html
D	target/classes/application.properties
D	target/classes/com/rentaroom/RentARoomApplication.class
D	target/classes/com/rentaroom/controller/AdminController.class
D	target/classes/com/rentaroom/controller/AuthController.class
D	target/classes/com/rentaroom/controller/BookingController.class
D	target/classes/com/rentaroom/controller/DashboardController.class
D	target/classes/com/rentaroom/controller/HomeController.class
D	target/classes/com/rentaroom/controller/PaymentController.class
D	target/classes/com/rentaroom/controller/RoomController.class
D	target/classes/com/rentaroom/converter/BookingStatusConverter.class
D	target/classes/com/rentaroom/converter/PaymentStatusConverter.class
D	target/classes/com/rentaroom/converter/RoleConverter.class
D	target/classes/com/rentaroom/dto/CreatePaymentIntentRequest.class
D	target/classes/com/rentaroom/dto/PaymentRequest.class
D	target/classes/com/rentaroom/dto/PaymentResponse.class
D	target/classes/com/rentaroom/model/Booking$BookingStatus.class
D	target/classes/com/rentaroom/model/Booking.class
D	target/classes/com/rentaroom/model/HostProfile.class
D	target/classes/com/rentaroom/model/Payment$PaymentStatus.class
D	target/classes/com/rentaroom/model/Payment.class
D	target/classes/com/rentaroom/model/Review.class
D	target/classes/com/rentaroom/model/Room.class
D	target/classes/com/rentaroom/model/User$Role.class
D	target/classes/com/rentaroom/model/User.class
D	target/classes/com/rentaroom/repository/BookingRepository.class
D	target/classes/com/rentaroom/repository/HostProfileRepository.class
D	target/classes/com/rentaroom/repository/PaymentRepository.class
D	target/classes/com/rentaroom/repository/ReviewRepository.class
D	target/classes/com/rentaroom/repository/RoomRepository.class
D	target/classes/com/rentaroom/repository/UserRepository.class
D	target/classes/com/rentaroom/service/AdminService.class
D	target/classes/com/rentaroom/service/BookingService.class
D	target/classes/com/rentaroom/service/HostProfileService.class
D	target/classes/com/rentaroom/service/PaymentService.class
D	target/classes/com/rentaroom/service/RoomService.class
D	target/classes/com/rentaroom/service/UserService.class
D	target/classes/static/css/style.css
D	target/classes/static/images/logo.svg
D	target/classes/static/js/main.js
D	target/classes/templates/admin/bookings.html
D	target/classes/templates/admin/dashboard.html
D	target/classes/templates/admin/payments.html
D	target/classes/templates/admin/rooms.html
D	target/classes/templates/admin/users.html
D	target/classes/templates/booking-detail.html
D	target/classes/templates/dashboard.html
D	target/classes/templates/host-profile.html
D	target/classes/templates/index.html
D	target/classes/templates/layout.html
D	target/classes/templates/login.html
D	target/classes/templates/my-bookings.html
D	target/classes/templates/register.html
D	target/classes/templates/room-detail.html
D	target/classes/templates/room-form.html
D	target/maven-archiver/pom.properties
D	target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
D	target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
D	target/rent-a-room-1.0.0.jar
D	target/rent-a-room-1.0.0.jar.original
