# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/rent_a_room?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=464913090Bmw.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Session Configuration
server.servlet.session.timeout=30m

# Stripe Configuration
# Get your API keys from https://dashboard.stripe.com/apikeys
stripe.secret.key=sk_test_51StyKmAw0stATI6QZnsKgbCZHn7w53GcQasHAs9unEKzckofjZWOT251HuSC1zxfGhXSdtSURnU8ZVfIvUYg63XP005ika8lJB
stripe.public.key=pk_test_51StyKmAw0stATI6QzLqa1hACj5UVL6cWdaRGzLy1JUwUih1nNmdrqs9DxYZapicsDRthC0Zmvq3yt0ryDUKCGLAX006BmH7p5b
stripe.currency=usd